# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - carprice-predictor

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://canadaianusedcarprice.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_8a110171e62c494bb20be5dc82676a28 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c5e5687946b54cc3bf7f211a5e33fec3 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: canadaianusedcarprice.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8a110171e62c494bb20be5dc82676a28 }}/carpricepredictor:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'carprice-predictor'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_de6db55108c94347996aa1177f17e209 }}
        images: 'canadaianusedcarprice.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8a110171e62c494bb20be5dc82676a28 }}/carpricepredictor:${{ github.sha }}'